### ISSUE TITLE
CORS 

### ISSUE THREAD

**Issue by alejo9420** [cdiaz/trmcol#6]
Buenas tardes, encontré este modulo y me pareció interesante agregarlo a una aplicación en angular 4 donde se requiere ver el valor de la trm del día.

Instale el modulo normalmente, pero luego al tratar de usarlo me sale el siguiente error:

![image](https://user-images.githubusercontent.com/21010991/33336312-76008e14-d43d-11e7-8677-c54cd4b8ec69.png)

Estuve investigando y el problema de cors parece ser de servidor. Espero que me puedan ayudar a resolver la duda y poder usar este módulo.

Cordialmente
Alejandro Ramirez

**Comment by DiegoRBaquero** [comment]
No se puede hacer nada, la configuración la tendría que hacer la superfinanciera.
